### ISSUE TITLE
L'autocompletion ne fonctionne pas bien

### ISSUE THREAD

**Issue by tfrancart** [CoopAxis/SMW_ToursTech#11]
L'autocompletion (sur le champ Contact par exemple) fonctionne pour l'instant en proposant en autocompletion les valeurs déjà saisies dans d'autres fiches. Il faut arriver à mettre une autocompletion avec toutes les pages d'une catégorie.

Voir http://www.mediawiki.org/wiki/Extension:Semantic_Forms/Defining_forms#Allowed_input_types_for_data_types notamment

Je n'arrive pas à paramétrer le field du Formulaire comme il faut.

**Comment by tfrancart** [comment]
Normalement, ce paramétrage dans le formulaire Organisation devrait être bon, mais ne fonctionne pas :

    ! Contact:
    | {{{field|Contact|property=ContactPoint|input type=text with autocomplete|values from category=Personne}}}

**Comment by tfrancart** [comment]
En écrivant "Person" à la place de "Personne" ca marche mieux :-) faudrait voir à normaliser nos choix de nommage de catégories/propriétés (tout en français) :

    ! Contact:
    | {{{field|Contact|property=ContactPoint|input type=text with autocomplete|values from category=Person}}}

**Comment by tfrancart** [comment]
OK, ca le fait :

Formulaire Organisation :

    |-
    ! Membres:
    | {{{field|Membres|input type=tokens|values from category=Person}}}

Modèle Organisation :

    Membres : {{#arraymap:{{{Membres|}}}|,|x|[[Has member::x]]}}

**Comment by Cyrille37** [comment]
On pourrait traiter le problème de nommage "fr" ou "en" Comme pour "Place" et "Lieu" ?
