### ISSUE TITLE
Supprimer les personnes du wiki

### ISSUE THREAD

**Issue by tfrancart** [CoopAxis/SMW_ToursTech#12]
Je pense qu'on ne devrait pas inclure les personnes physiques dans le wiki. Pour deux raisons :

1. on prête le flanc de façon évidente au remarques sur le CNIL et la vie privée, etc (cf dernière réunion)
2. les personnes changent, bougent, les organisations restent.

La seule exception que je vois serait pour les auto-entrepreneurs, ça a du sens de les mettre puisqu'ils ont un statut social "public".

Qu'en pensez-vous ?

**Comment by Cyrille37** [comment]
Je  suis bien d'accord, en même temps il y a des "stars" que l'on souhaitera voir apparaître.
Le compromis pourrait être de n'avoir que les personnes qui se sont "elles-même" rentrées dans le wiki.
