### ISSUE TITLE
Paramétrer une redirection http depuis "../sparql" vers ".../openrdf-sesame/repositories/smw-coopaxis"

### ISSUE THREAD

**Issue by tfrancart** [CoopAxis/SMW_ToursTech#13]
Cyrille pourrais-tu paramétrer une redirection nginx pour rediriger :

http://smw.coopaxis.fr/sparql

vers

http://smw.coopaxis.fr/openrdf-sesame/repositories/smw-coopaxis

Merci

**Comment by Cyrille37** [comment]
J'ai ajouté ça
        location /sparql {
                rewrite ^ http://smw.coopaxis.fr/openrdf-sesame/repositories/smw-coopaxis permanent;
        }
J'espère que ça fonctionne. Dis moi.

**Comment by tfrancart** [comment]
Ca marche, mais le redirect n'est pas supporté par tous les outils. Gephi en particulier ne supporte pas. Tu peux mettre un alias à la place ?

**Comment by Cyrille37** [comment]
J'ai remplacé avec ça, mais aucune idée si ça fonctionne mieux ...

        location /sparql {
                # Ok, mais pas avec Gephi
                #rewrite ^ http://smw.coopaxis.fr/openrdf-sesame/repositories/smw-coopaxis permanent;
                rewrite ^/sparql(.*)$ /openrdf-sesame/repositories/smw-coopaxis$1;
        }
