### ISSUE TITLE
Activer CORS sur le serveur Sesame pour qu'on puisse l'interroger en Ajax

### ISSUE THREAD

**Issue by tfrancart** [CoopAxis/SMW_ToursTech#14]
Voir https://github.com/CoopAxis/SMW_ToursTech/blob/master/sparql/sparql-form.htm
Ne marche pas pour l'instant car Sesame ne supporte pas encore JSONP. On pourrait activer CORS sur le serveur Tomcat pour autoriser les requêtes via Javascript.

Ca doit s'activer comme ca : http://tomcat.apache.org/tomcat-7.0-doc/config/filter.html#CORS_Filter

Ou bien il y a quelque chose au niveau Nginx ?
Cyrille tu en sais plus ?

Ca permettrait de connecter les données du wiki à des bibliothèques Javascript (Antoine regardait Raphael JS : http://raphaeljs.com/), donc hyper important pour maximiser la réutilisation des données par des developpeurs web.

**Comment by Cyrille37** [comment]
C'est activé.
Pas essayer, juste vérifié que les headers du serveur contenaient bien le header
 Access-Control-Allow-Origin *

**Comment by tfrancart** [comment]
Le comportement a bien changé par rapport à avant, mais la réponse du serveur est bizarre. Voilà ce que j'ai dans la Response :

Recharger la page pour obtenir le code source pour: http://smw.coopaxis.fr/openrdf-sesame/repositories/smw-coopaxis?query=PREFIX%20rdfs%3A%20%3Chttp%3A//www.w3.org/2000/01/rdf-schema%23%3E%0APREFIX%20rdf%3A%20%3Chttp%3A//www.w3.org/1999/02/22-rdf-syntax-ns%23%3E%0APREFIX%20xsd%3A%20%3Chttp%3A//www.w3.org/2001/XMLSchema%23%3E%0APREFIX%20owl%3A%20%3Chttp%3A//www.w3.org/2002/07/owl%23%3E%0APREFIX%20skos%3A%20%3Chttp%3A//www.w3.org/2004/02/skos/core%23%3E%0APREFIX%20schema%3A%20%3Chttp%3A//schema.org/%3E%0ASELECT%20%3Fs%20%3Fp%20%3Fo%0AWHERE%20%7B%0A%20%20%3Fs%20%3Fp%20%3Fo%0A%7D%20LIMIT%2010%0A%20%20%20%20%20%20&format=json&callback=jQuery1111012181472991389397_1423063069885&_=1423063069886

Je m'attends à un flux JSON ou XML en retour

**Comment by Cyrille37** [comment]
Le lien que tu indiques retourne bien du XML. Mon Firefox me propose d'enregistrer le fichier "query-result.srx" qui contient bien du XML avec comme noeud racine &lt;sparql xmlns='http://www.w3.org/2005/sparql-results#'&gt;

C'est peut être le "Content-type" qui ne va pas ?
