### ISSUE TITLE
Extraire un graph des données

### ISSUE THREAD

**Issue by Cyrille37** [CoopAxis/SMW_ToursTech#2]
Il faudrait mettre en exemple l'extraction d'un graph des données.

* Comment faire ?
* Quel format ?
* Quelle visualisation ?

**Comment by Cyrille37** [comment]
Maintenant que l'on a un peu de donner, il faudrait donner à voir un graph ;-)
Quelle chaîne logicielle ?

**Comment by tfrancart** [comment]
Dans un premier temps je vous montrerai un outil tout près qui fonctionne avec les données RDF du wiki : RelFinder (http://relfinder.dbpedia.org). Il faut charger une petite config qui va bien, et ensuite on peut répondre à la question "Mais tiens donc, quel est le lien dans le graphe entre Sparna et Cyrille Giquello" ? et là on a un beau graphe qui se construit sous nos yeux. Je l'ai fait, il y a un effet "wahou" intéressant.

Pitch :

1. les données sont réutilisables par d'autres applications
2. les données forment un graphe
3. ces données permettent de répondre à des questions qui autrement n'auraient pas de réponse

**Comment by tfrancart** [comment]
J'ai essayé rapidement Gephi (http://gephi.github.io/), avec l'extension SemanticWebImport (https://wiki.gephi.org/index.php/SemanticWebImport). On arrive facilement à le connecter à nos données dans Sesame et à sortir un graphe. Donc pas de souci pour ce qui est de l'interconnexion des données; après, il y a plein de fonctions dans Gephi qu'il faut prendre le temps de creuser pour sortir quelque chose de joli, mais "y'a plus qu'à" !
Je peaufinerai un peu et je mettrai dans ce Git le fichier de config Gephi qui va bien (comme pour RelFinder)

**Comment by Cyrille37** [comment]
C'est la classe ! ;-)

**Comment by tfrancart** [comment]
Je vous invite à aller voir le premier résultat d'un export du graphe un peu propre avec Gephi : https://github.com/CoopAxis/SMW_ToursTech/tree/master/Gephi (voir le fichier PNG). Il y aurait encore beaucoup de choses à faire pour avoir un rendu joli, mais c'est un début.

Par ailleurs les fichiers de config Gephi+SemanticWebImport qui vont bien sont dans le même répertoire.

**Comment by antoine37120** [comment]
Voici un 2 exemples réalisés grâce à la bibliothèque Sigmajs http://sigmajs.org/

Le premier est réalisé à partir d'un export de la cartographie réalisée par Thomas via Gephi (format .gexf) : 
http://www.cartographie.mwebius.com/index2.html

Le second à partir de données récupérées en temps réel et avec un exemple de filtres sur le nombre de lien d'une organisation ou d'une personne:
http://www.cartographie.mwebius.com/

**Comment by tfrancart** [comment]
Chouette !
J'ai modifié le script Gephi pour exporter un fichier gexf automatiquement, accessible à http://smw.coopaxis.fr/carto/carto.gexf
Ce fichier est regénéré toutes les heures, en même temps que http://smw.coopaxis.fr/carto/carto.png

**Comment by antoine37120** [comment]
Le contenue du fichier est en binaire, il faudrait normalement du XML




-- 

Antoine DUPRÉ
DT | Developpeur
antoine@mwebius.com
06 45 37 44 13

MWEBIUS PROJECTCréateurs d'échange durable
Agence de Communication Visuelle
30 rue André Theuriet | 37000 TOURS
www.mwebiusproject.com

**Comment by tfrancart** [comment]
Oui effectivement... ca le fait maintenant, donc à http://smw.coopaxis.fr/carto/carto.gexf

**Comment by antoine37120** [comment]
C'est bon le lien est à jour et ça fonctionne.




-- 

Antoine DUPRÉ
DT | Developpeur
antoine@mwebius.com
06 45 37 44 13

MWEBIUS PROJECTCréateurs d'échange durable
Agence de Communication Visuelle
30 rue André Theuriet | 37000 TOURS
www.mwebiusproject.com




2015-02-05 19:18 GMT+01:00 tfrancart <notifications@github.com>:

**Comment by antoine37120** [comment]
J'ai réalisé d'autres changements notamment forcé le rendu sans webgl pour
garder le plus de fonction possibles disponibles.

c'est en faisant et en utilisant que les idées d’amélioration viennent.





-- 

Antoine DUPRÉ
DT | Developpeur
antoine@mwebius.com
06 45 37 44 13

MWEBIUS PROJECTCréateurs d'échange durable
Agence de Communication Visuelle
30 rue André Theuriet | 37000 TOURS
www.mwebiusproject.com

**Comment by Cyrille37** [comment]
@antoine37120 il y a un problème avec les caractères accentués sur http://www.cartographie.mwebius.com/ alors qu'ils passent très bien sur http://www.cartographie.mwebius.com/index2.html
