### ISSUE TITLE
Requètes open-rdf (sésame) HS

### ISSUE THREAD

**Issue by antoine37120** [CoopAxis/SMW_ToursTech#4]
L'exemple de requête suivant ne fonctionne plus:
{{#ask:[[Catégorie:Organisation]]}}
Il semble que toutes les requêtes écrites manuellement ne fonctionnent plus.

**Comment by Cyrille37** [comment]
Nous sommes repassé en mode full SMW et un export régulier vers OPEN-RDF (Sesame).
Il reste des bugs dans SMW ...
