### ISSUE TITLE
adresse Facebook

### ISSUE THREAD

**Issue by Cyrille37** [CoopAxis/SMW_ToursTech#5]
Ça serait bien de ne mettre que le nom de la page facebook sans l'url.

Par exemple "centre.tic" au lieu de "https://www.facebook.com/centre.tic"

**Comment by Cyrille37** [comment]
Actuellement le modèle à un problème, l'adresse facebook n'est pas rendu comme un lien.

**Comment by antoine37120** [comment]
Pas évidant, avec l'URL ce n'est pas plus facile est plus sûr pour
retrouver la page?
Le 11 janv. 2015 12:18, "Cyrille Giquello" <notifications@github.com> a
écrit :

**Comment by Cyrille37** [comment]
Ben on fait souvent ça comme la donnée est qualifiée comme un "lien web vers Facebook" c'est au programmes utilisateurs de faire le boulot ;-)

**Comment by Cyrille37** [comment]
Et puis Actuellement le modèle à un problème, l'adresse facebook n'est pas rendu comme un lien quand on met l'url complète ;-)

**Comment by antoine37120** [comment]
Je ne suis pas chez moi, je vérifierai le modèle après avoir sélectionné
son contenu.
Le 11 janv. 2015 12:31, "Cyrille Giquello" <notifications@github.com> a
écrit :

**Comment by tfrancart** [comment]
Le problème vient de ce que la page de la propriété Facebook URL n'existe pas dans le wiki. Il faut la créer, en lui donnant un type "URL". D'ailleurs toutes les propriétés listées en rouge dans la liste à http://smw.coopaxis.fr/Sp%C3%A9cial:Propri%C3%A9t%C3%A9s sont anormales. Soit elles sont à supprimer, soit il faut créer la page. Antoine tu prends cette action ?

**Comment by antoine37120** [comment]
Ok mais c'est pas grave si c'est pas maintenant?
Nous avions décidé de travailler tous les trois aujourd'hui?

**Comment by Cyrille37** [comment]
Non ce n'est pas grave. Pour que tu t'en souvienne je t'ai assigné la tâche ;-)

**Comment by antoine37120** [comment]
J'ai u peur d'avoir zappé ;-)
Le 11 janv. 2015 20:28, "Cyrille Giquello" <notifications@github.com> a
écrit :

**Comment by Cyrille37** [comment]
Ok, c'est fait: j'ai créé la page pour la propriété http://smw.coopaxis.fr/Attribut:Facebook_url

J'ai aussi ajouté "C'est une sous-propriété de [[subproperty of::Property:URL]]". Je me dis que ça doit pouvoir servir pour des requêtes ... Mais pas sûr ;-)
