### ISSUE TITLE
Nom et Autre nom (Raison sociale)

### ISSUE THREAD

**Issue by Cyrille37** [CoopAxis/SMW_ToursTech#6]
Faut il conserver le champs "Autre nom" ou le remplacer par "Raison Sociale" ?

Exemple:
Toute sa communication est faite avec le nom "Addicti" du coup c'est logique que la page du Wiki soit "Addictic", surtout pour les relations (Is Member Of). Mais sa raison sociale est "DG Support".
Voir:
- http://smw.coopaxis.fr/ADDICTIC
- http://www.societe.com/societe/dg-support-498295039.html

**Comment by tfrancart** [comment]
1. Oui c'est logique de nommer la page du wiki par le nom le plus connu.
2. Je pense qu'il faut garder "Autre nom" pour des cas de synonymie type "Cantine numérique / Palo Altours"
3. Attention nous avons déjà http://smw.coopaxis.fr/Attribut:LegalName qui correspond exactement à la notion de raison sociale. On renomme cet attribut pour que ce soit plus clair ?

**Comment by tfrancart** [comment]
J'ai modifié le formulaire et le modèle pour remplacer le champ "Nom" par "Raison sociale" ce qui est plus clair. Du coup, pour des cas pour ADDICTIC :

1. On créé la page sous le nom le plus connu
2. On met la raison sociale dans le champ "raison sociale", qui vient remplir l'attribut legalName
3. On peut toujours utiliser le champ "autre noms" pour mettre des alias

C'est ce que j'ai fait en modifiant la fiche http://smw.coopaxis.fr/ADDICTIC

Qu'en penses-tu ?

**Comment by Cyrille37** [comment]
Documenter sur http://smw.coopaxis.fr/Aide:Accueil#Nom.28s.29_des_organisations
