### ISSUE TITLE
Données sans affichage (CA, ...)

### ISSUE THREAD

**Issue by Cyrille37** [CoopAxis/SMW_ToursTech#7]
Dans les données je renseigne le code APE et le chiffre d'affaire 2013.

Peut-être les ajouter au formulaire, mais pas au modèle de boite (en haut à droite) ?
Comme ça on ne l'affiche pas, mais ces données sont disponibles.

D'autres champs sont peut-être à traiter de cette façon ?

**Comment by tfrancart** [comment]
Oui, ca doit être possible.

1. Tu ajoutes ton champ dans le formulaire comme d'hab.
2. Dans le modèle, tu utilises la syntaxe documentée à https://semantic-mediawiki.org/wiki/Help:Properties_and_types#Turning_links_into_properties pour que la propriété ne s'affiche pas :

    To hide the property [[Example property::link| ]] from appearing at all use a space as the alternate text.

(mettre un espace après le pipe).
Et dans le modèle tu peux mettre cette propriété en bas de page par exemple, pas dans la boite en haut à droite.

Ceci dit, même si la valeur n'apparait pas dans la page, il suffira de faire une modification avec le formulaire pour la voir...

**Comment by tfrancart** [comment]
J'ai fait la manip en ajoutant la propriété http://smw.coopaxis.fr/Attribut:Code_APE
Regarde le modèle http://smw.coopaxis.fr/Mod%C3%A8le:Organisation
et le formulaire http://smw.coopaxis.fr/Formulaire:Organisation
Je l'ai saisie sur http://smw.coopaxis.fr/Sparna, on a bien la valeur dans les données sans que cela apparaisse dans la page. Mais on voit la valeur si on édite via le formulaire.

**Comment by Cyrille37** [comment]
Documenter sur http://smw.coopaxis.fr/Aide:Accueil#Donn.C3.A9es_sans_affichage
