### ISSUE TITLE
problème pour désactiver Cache

### ISSUE THREAD

**Issue by Cyrille37** [CoopAxis/SMW_ToursTech#8]
Je n'arrive pas à désactiver complètement le cache. Pendant la saisie c'est bien de pouvoir consulter les résultats pour vérifier qu'il n'y a pas d'erreur.

J'ai essayé tous plein de paramètres dans LocalSettings mais nada ...

**Comment by tfrancart** [comment]
Quel est le problème ? si c'est une "inline query" qui ne se rafraichit pas tout de suite, est-ce que cette explication t'aide ? https://semantic-mediawiki.org/wiki/FAQ#Why_doesn.27t_data_I_have_just_added_show_up_in_queries.3F (dans le menu des onglets, près du champs de recherche en haut à droite, lien "Rafraichir")

**Comment by Cyrille37** [comment]
Merci Thomas, c'est bien ça.
Je mets à jour http://smw.coopaxis.fr/Aide:Accueil

**Comment by Cyrille37** [comment]
Documenter sur http://smw.coopaxis.fr/Aide:Accueil#Cache
