### ISSUE TITLE
Profession Libérale, Entreprise personnelle ...

### ISSUE THREAD

**Issue by Cyrille37** [CoopAxis/SMW_ToursTech#9]
Pour les professions libérales et autres organisations avec le même nom pour la personne Morale et la personne Physique, je propose de mettre la "page wiki" dans les 2 catégories "Organisation" et "Person".

**Comment by tfrancart** [comment]
Ca pourrait devenir confus, car en listant les organisations, on va se retrouver avec ces personnes là. Je verrai bien une Catégorie à part entière "Profession libérale / entreprise individuelle"; cette nouvelle catégorie pourrait être sous-catégorie de Person et Organisation à la fois ?

**Comment by Cyrille37** [comment]
En fait je remarque qu'il n'y a pas beaucoup de gens qui n'ont pas d'*enseigne*. Du coup l'enseigne dans "organisation" et le nom dans "person". C'est un peu batard, mais je viens de faire tout plein de saisies de cette façon:
http://smw.coopaxis.fr/InnoVAticE
http://smw.coopaxis.fr/Graphikoo

Pour en rajouter à la "non normalisation" il y en à pour lesquels je ne trouve aucun SIREN ... Surement des auto-entrepreneurs.
